# AI Thought Capture - LTF Influencer Manifest

project:
  name: "ai-thought-capture"
  mnemonic: "atc" # AI Thought Capture
  type: "app"
  repo: "https://github.com/cashmy/living-task-framework"
  branch: "main"
  lifecycle: "active"

influencers:
  # Core concept files
  concept:
    - "projects/ai-thought-capture/Concept.md"
    - "projects/ai-thought-capture/Problem_description.md"
    - "projects/ai-thought-capture/Brand_Analysis.md"

  # Architecture & design
  architecture:
    - "projects/ai-thought-capture/architecture/architecture_diagram.md"

  # Project planning
  planning:
    - "projects/ai-thought-capture/High_Level_Tasks.md"
    - "projects/ai-thought-capture/Actual Steps.md"
    - "projects/ai-thought-capture/Current CIP.md"

  # Technical documentation
  technical:
    - "projects/ai-thought-capture/docs/watcher_PURPOSE.md"
    - "projects/ai-thought-capture/NOTE_echo_forge.md"

auto_detect:
  enabled: true
  rules:
    - pattern: "docs/**/*.md"
      category: "documentation"
      priority: medium
    - pattern: "tests/**/*.py"
      category: "tests"
      priority: medium

lifecycle_config:
  active:
    snapshot_frequency: "medium"
    cognitive_depth: "standard"
